- hosts: all
  vars_files:
    - ../defaults/main.yaml
  handlers:
  - import_tasks: ../handlers/main.yml

  tasks:
  - name: Monitor the install progress
    environment:
      KUBECONFIG: "{{ workdir }}/auth/kubeconfig"
    include_tasks: day2-csr.yaml