---
# tasks file for download ocp files
  - name: Delete OCP4 files, if requested, to download again
    file:
         state: absent
         path: "{{ item }}"
    with_items:
        - "/usr/local/src/openshift-client-linux.tar.gz"
        - "/usr/local/src/openshift-install-linux.tar.gz"
        - "/usr/local/src/rhcos-live-{{ rhcos_arch }}.iso"
        - "/var/www/html/install/rootfs.img"
        - "/var/lib/tftpboot/rhcos/initramfs.img"
        - "/var/lib/tftpboot/rhcos/kernel"
    when: force_ocp_download

  # - name: Downloading OCP4 rhcos-live.iso
  #   when: rhcos_iso is defined
  #   get_url:
  #       url: "{{ rhcos_iso }}"
  #       dest: "/usr/local/src/rhcos-live-{{ rhcos_arch }}.iso"
  #       mode: 0555

  - name: Downloading OCP4 installer initramfs
    get_url:
      url: "{{ rhcos_initramfs }}"
      dest: /var/lib/tftpboot/rhcos/initramfs.img
      mode: 0555

  - name: Downloading OCP4 installer kernel
    get_url:
      url: "{{ rhcos_kernel }}"
      dest: /var/lib/tftpboot/rhcos/kernel
      mode: 0555

  - name: Downloading OCP4 installer rootfs
    get_url:
      url: "{{ rhcos_rootfs }}"
      dest: /var/www/html/install/rootfs.img
      mode: 0555

  - name: Preparing OCP client
    when: ocp_client is defined
    block:
    - name: Downloading OCP4 client
      get_url:
        url: "{{ ocp_client }}"
        dest: /usr/local/src/openshift-client-linux.tar.gz

    - name: Unarchiving OCP4 client
      unarchive:
        src: /usr/local/src/openshift-client-linux.tar.gz
        dest: /usr/local/bin
        remote_src: yes

  - name: Preparing OCP installer
    when: ocp_installer is defined
    block:
    - name: Downloading OCP4 Installer
      get_url:
        url: "{{ ocp_installer }}"
        dest: /usr/local/src/openshift-install-linux.tar.gz

    - name: Unarchiving OCP4 Installer
      unarchive:
        src: /usr/local/src/openshift-install-linux.tar.gz
        dest: /usr/local/bin
        remote_src: yes

  - name: Removing files that are not needed
    file:
      path: /usr/local/bin/README.md
      state: absent
