---
- name: create grub2 block
  blockinfile:
    marker: ""
    content: |
      if [ ${net_default_mac} == {{ mac }} ]; then
      default=0
      fallback=1
      timeout=1
      menuentry "CoreOS (BIOS)" {
         echo "Loading kernel"
         linux "/rhcos/kernel" ip=dhcp rd.neednet=1 ignition.platform.id=metal ignition.firstboot coreos.live.rootfs_url=http://{{ helper.ipaddr }}:8080/install/rootfs.img ignition.config.url=http://{{ helper.ipaddr }}:8080/ignition/sno.ign

         echo "Loading initrd"
         initrd  "/rhcos/initramfs.img"
      }
      fi
    dest: /var/lib/tftpboot/boot/grub2/grub.cfg

