---
- name: create grub2 block
  when: ignition == "sno.ign"
  blockinfile:
    marker: ""
    content: |
      if [ ${net_default_mac} == {{ mac }} ]; then
      default=0
      fallback=1
      timeout=1
      menuentry "CoreOS (BIOS)" {
         echo "Loading kernel"
         linux "/rhcos/kernel" ip=dhcp rd.neednet=1 ignition.platform.id=metal ignition.firstboot {{ coreos_inst_url }} ignition.config.url={{ ignition_url }}/{{ ignition }}

         echo "Loading initrd"
         initrd  "/rhcos/initramfs.img"
      }
      fi
    dest: /var/lib/tftpboot/boot/grub2/grub.cfg

- name: create grub2 block for day2 worker
  when: ignition == "day2-worker.ign"
  blockinfile:
    marker: ""
    content: |
      if [ ${net_default_mac} == {{ mac }} ]; then
      default=0
      fallback=1
      timeout=1
      menuentry "CoreOS (BIOS)" {
         echo "Loading kernel"
         linux "/rhcos/kernel" ip=dhcp rd.neednet=1 coreos.inst=yes coreos.inst.install_dev={{ mdisk }} {{ coreos_inst_url }} coreos.inst.ignition_url={{ ignition_url }}/{{ ignition }} ignition.config.url={{ ignition_url }}/first-boot-day2-ppc64le.ign

         echo "Loading initrd"
         initrd  "/rhcos/initramfs.img"
      }
      fi
    dest: /var/lib/tftpboot/boot/grub2/grub.cfg

