---
# tasks file for netboot nodes
- name: netboot sno node
  shell: |
    orig_mac={{ sno.macaddr }}
    pvm_mac=`echo ${orig_mac//:}`
    pvmcec={{ sno.pvmcec }}
    pvmlpar={{ sno.pvmlpar }}
    pvm_profile=`ssh -o StrictHostKeyChecking=no {{ pvm_hmc }} "lssyscfg -r lpar -m ${pvmcec} --filter lpar_names=${pvmlpar} -F curr_profile"`
    remote_cmd="lpar_netboot -i -D -f -t ent -m ${pvm_mac} -s auto -d auto -S {{ helper.ipaddr }} -C {{ sno.ipaddr }} -G {{ dhcp.router }} ${pvmlpar} ${pvm_profile} ${pvmcec}"
    ssh -o StrictHostKeyChecking=no {{ pvm_hmc }} "${remote_cmd}"
