- hosts: all
  vars_files:
    - ../defaults/main.yaml
  handlers:
  - import_tasks: ../handlers/main.yml
    
  tasks:
  - name: Set setup facts
    include_tasks: set_facts.yaml

  - name: Check connection
    wait_for_connection:
      delay: 15
      connect_timeout: 15
      timeout: "{{ node_connection_timeout }}"
      
  - name: Wait for install-complete
    shell: "openshift-install wait-for install-complete --log-level {{ log_level }}"
    args:
      chdir: "{{ workdir }}"

  - name: Configure nfs-provisioner
    shell: helpernodecheck nfs-setup
    when: storage_type == "nfs"

  # The image-registry is not always available immediately after the OCP installer
  - name: Wait for image-registry operator
    shell: "oc get configs.imageregistry.operator.openshift.io/cluster --no-headers | wc -l"
    register: imgreg_operator_count
    until: imgreg_operator_count.stdout|int > 0
    retries: 20
    delay: 30

  - name: Create and patch image-registry operator as registry-pvc
    tags: image-registry
    shell: |
      oc create -f /usr/local/src/registry-pvc.yaml -n openshift-image-registry
      oc patch configs.imageregistry.operator.openshift.io cluster --type merge --patch '{"spec":{"storage":{"pvc":{ "claim": "registry-pvc"}}, "managementState": "Managed"}}'
    when: storage_type == "nfs"

  - name: Patch image-registry operator as emptyDir
    tags: image-registry
    shell: |
      oc patch configs.imageregistry.operator.openshift.io cluster --type merge --patch '{"spec":{"storage":{"emptyDir":{}}, "managementState": "Managed"}}'
    when: storage_type != "nfs"
