---
- block:
    - assert: 
        that: "{{ helper.networkifacename is defined }}"
    - set_fact: 
        networkifacename: "{{ helper.networkifacename }}"
  rescue:
    - set_fact:
        networkifacename: "{{ ansible_default_ipv4.interface }}"


- set_fact:
      packages:
        - dnsmasq
        - bind-utils
        - firewalld
        - httpd
        - bash-completion
        - coreos-installer

  
- set_fact:
      services:
        - dnsmasq
        - httpd

- set_fact:
      ports:
        - 67/udp
        - 53/tcp
        - 53/udp
        - 443/tcp
        - 80/tcp
        - 8080/tcp
        - 6443/tcp
        - 6443/udp
        - 22623/tcp
        - 22623/udp
        - 69/udp
        - 111/tcp
        - 2049/tcp
        - 20048/tcp
        - 50825/tcp
        - 53248/tcp

