---
- block:
    - assert: 
        that: "{{ helper.networkifacename is defined }}"
    - set_fact: 
        networkifacename: "{{ helper.networkifacename }}"
  rescue:
    - set_fact:
        networkifacename: "{{ ansible_default_ipv4.interface }}"

- block:
  - set_fact:
      registry:
        - podman
        - jq

  - set_fact:
      registry_services:
        - dnsmasq
        - firewalld
        - local-registry

  - set_fact:
      registry_host: "registry.{{ dns.clusterid }}.{{ dns.domain | lower  }}"
      local_registry: "registry.{{ dns.clusterid }}.{{ dns.domain | lower  }}:5000"
      release_image: "{{ setup_registry.remote_registry | default('quay.io') }}/{{ setup_registry.product_repo }}/{{ setup_registry.release_name }}:{{ setup_registry.release_tag }}"

- set_fact:
      packages:
        - dnsmasq
        - bind-utils
        - firewalld
        - httpd
        - httpd-tools
        - bash-completion
        - coreos-installer
        - nfs-utils
        - vim
  
- set_fact:
      services:
        - dnsmasq
        - httpd
        - nfs-server

- set_fact:
      ports:
        - 67/udp
        - 53/tcp
        - 53/udp
        - 443/tcp
        - 80/tcp
        - 8080/tcp
        - 6443/tcp
        - 6443/udp
        - 22623/tcp
        - 22623/udp
        - 69/udp
        - 111/tcp
        - 2049/tcp
        - 20048/tcp
        - 50825/tcp
        - 53248/tcp

# See Fedora Wiki for changes:
# https://fedoraproject.org/wiki/Changes/RenameNobodyUser
- set_fact:
    owner: nobody
    group: nobody
