---
# tasks file for config services
  - name: Install needed packages
    package:
      name: "{{ packages }}"
      state: present

  - name: Remove existing config files
    import_tasks: remove_old_config_files.yaml
    #when: remove_old_config_files

  - name: Write out dnsmasq's addnhosts file
    template:
      src: ../templates/addnhosts.j2
      dest: /etc/dnsmasq.d/addnhosts

  - name: Write out dnsmasq file
    template:
      src: ../templates/dnsmasq.conf.j2
      dest: /etc/dnsmasq.conf
    notify:
      - restart dnsmasq

  - name: Set HTTP server and prepare OCP4 bios
    block:
    - name: Copy httpd conf file
      copy:
        src: ../files/httpd.conf
        dest: /etc/httpd/conf/httpd.conf
      notify:
        - restart httpd

  - name: Create apache directories for installing
    file:
        path: "{{ item }}"
        state: directory
        mode: 0755
    with_items:
        - /var/www/html/install
        - /var/www/html/ignition

  - name: Create NFS export directory
    file:
      path: /export
      state: directory
      mode: 0777
      owner: "{{ owner }}"
      group: "{{ group }}"
    notify:
      - restart nfs

  - name: Copy NFS export conf file
    copy:
      src: ../files/nfs-exports
      dest: /etc/exports
    notify:
      - restart nfs

  - name: Copying over nfs-provisioner rbac
    copy:
      src: ../files/nfs-provisioner-rbac.yaml
      dest: /usr/local/src/nfs-provisioner-rbac.yaml
      owner: root
      group: root
      mode: 0666

  - name: Copying over nfs-provisioner deployment
    template:
      src: ../templates/nfs-provisioner-deployment.yaml.j2
      dest: /usr/local/src/nfs-provisioner-deployment.yaml
      owner: root
      group: root
      mode: 0666

  - name: Copying over nfs-provisioner storageclass
    copy:
      src: ../files/nfs-provisioner-sc.yaml
      dest: /usr/local/src/nfs-provisioner-sc.yaml
      owner: root
      group: root
      mode: 0666

  - name: Copying over nfs-provisioner setup script
    copy:
      src: ../files/nfs-provisioner-setup.sh
      dest: /usr/local/bin/nfs-provisioner-setup.sh
      owner: root
      group: root
      mode: 0555

  - name: Copying over a sample PVC file for NFS
    copy:
      src: ../files/registry-pvc.yaml
      dest: /usr/local/src/registry-pvc.yaml
      mode: '0555'

  - name: Copy info script over
    template:
      src: ../templates/checker.sh.j2
      dest: /usr/local/bin/helpernodecheck
      owner: root
      group: root
      mode: 0555

      