# tasks for setup tftp

  - name: generate netboot entry for grub2
    shell: grub2-mknetdir --net-directory=/var/lib/tftpboot

  - name: Create TFTP RHCOS dir
    file:
      path: /var/lib/tftpboot/rhcos
      state: directory
      mode: 0755
 
  - name: Generate grub2 config files
    block:
    - set_fact:
        install_url: "http://{{ helper.ipaddr }}:8080/install"
        ignition_url: "http://{{ helper.ipaddr }}:8080/ignition"
        coreos_inst_url: "coreos.live.rootfs_url=http://{{ helper.ipaddr }}:8080/install/rootfs.img"

    - name: create grub.cfg
      copy:
        dest: /var/lib/tftpboot/boot/grub2/grub.cfg
        content: |
          default=0
          fallback=1
          timeout=1
    
    - name: generate grub entry
      vars:
        ignition: "sno.ign"
        mac: "{{ sno.macaddr }}"
        mdisk: "{{ sno.disk }}"
      include_tasks: generate_grub.yaml

    - name: generate grub entry for day2_worker
      when: day2_worker is defined
      vars:
        ignition: "day2-worker.ign"
        mac: "{{ day2_worker.macaddr }}"
        mdisk: "{{ day2_worker.disk }}"
      include_tasks: generate_grub.yaml

  # fix the lpar_netboot failed to get PXE files under SELinux
  - name: Sel file label to tftpdir_rw_t
    shell: |
      semanage fcontext -a -t tftpdir_rw_t "/var/lib/tftpboot(/.*)?"
      semanage fcontext -a -t tftpdir_rw_t "/var/lib/tftpboot/boot(/.*)?"
      semanage fcontext -a -t tftpdir_rw_t "/var/lib/tftpboot/boot/grub2(/.*)?"
      semanage fcontext -a -t tftpdir_rw_t "/var/lib/tftpboot/boot/grub2/powerpc-ieee1275(/.*)?"
      restorecon -R -v /var/lib/tftpboot
      cp /var/lib/tftpboot/boot/grub2/powerpc-ieee1275/grub.cfg /var/lib/tftpboot/boot/grub2/powerpc-ieee1275/grub.cfg-0